# Generated by Django 3.2.12 on 2022-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardaddon',
            fields=[
                ('ba_idx', models.AutoField(primary_key=True, serialize=False)),
                ('ba_uuid', models.BinaryField(editable=True, max_length=16)),
                ('ba_tablename', models.CharField(db_column='ba_tableName', max_length=15)),
                ('ba_type', models.CharField(max_length=15)),
                ('ba_boardid', models.IntegerField(db_column='ba_boardID')),
                ('ba_commentid', models.IntegerField(db_column='ba_commentID', null=True)),
            ],
            options={
                'db_table': 'boardAddon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mainparty',
            fields=[
                ('mp_uid', models.AutoField(primary_key=True, serialize=False)),
                ('mp_wdate', models.CharField(max_length=19)),
                ('mp_writer', models.CharField(max_length=16)),
                ('mp_title', models.CharField(max_length=20)),
                ('mp_type', models.CharField(max_length=20)),
                ('mp_place', models.CharField(max_length=20)),
                ('mp_content', models.TextField()),
                ('mp_pricem', models.IntegerField(db_column='mp_priceM')),
                ('mp_pricef', models.IntegerField(db_column='mp_priceF')),
                ('mp_ablem', models.SmallIntegerField(db_column='mp_ableM')),
                ('mp_ablef', models.SmallIntegerField(db_column='mp_ableF')),
                ('mp_condm', models.IntegerField(db_column='mp_condM')),
                ('mp_condf', models.IntegerField(db_column='mp_condF')),
                ('mp_like', models.IntegerField()),
                ('mp_mdate', models.CharField(max_length=19)),
                ('mp_support', models.CharField(blank=True, max_length=45, null=True)),
                ('mp_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mainparty',
                'managed': False,
            },
        ),
    ]
